@startditaa -E
Architecture Classic Diagnostic Adapter

                               +-----------------------------------+        +-----------------+
                               | SOVD                              |        |  Plugins        |
                               +----------------+------------------+<-------+ +-------------+ |
                               |   HTTP-Server  |      OpenAPI     |        | :  Security   : |
                               +----------------+------------------+        | +-------------+ |
                                                |                           | :   Logging   : |
                                                |                           | +-------------+ |
                                                v                           | :   Tracing   : |
+----------------------+       +-----------------------------------+        | +-------------+ |
| Communication Layer  |       |       Diagnostic Tester           |        | :   Safety    : |
|                      |       |                                   |        | +-------------+ |
|+---------+----------+|<------+                                   |        |                 |
||  DoIP   |   UDS    ||       |                                   |        |                 |
|+---------+----------+|       |                                   |        |                 |
|                      |       |                                   |        |                 |
|                      |       |                                   |        |                 |
|                      |       |                                   |        |                 |
|                      |       |                                   |        |                 |
|                      |       |  +-----------------------------+  |        |                 |
|                      |       |  |  ECU Management / Detection |  |        |                 |
|                      |       |  +-----------------------------+  |        |                 |
|                      |       |                                   |        |                 |
|                      |       |  +-----------------------------+  |<-------+                 |
|                      |       |  |        UDS Payload          |  |        |                 |
|                      |       |  |         Converter           |  |        |                 |
|                      |       |  +------------+----------------+  |        |                 |
|                      |       |               |                   |        |                 |
|                      |       |               v                   |        |                 |
|                      |       |  +-----------------------------+  |        |                 |
|                      |       |  |   Diagnostic Database       |  |        |                 |
|                      |       |  +-----------------------------+  |        |                 |
|                      |       +-----------------------------------+        |                 |
|                      |                        ^                           |                 |
|                      |                        |                           |                 |
|                      |<-----------------------|---------------------------+                 |
|                      |                        |                           |                 |
|                      |       +------+     +---+--+                        |                 |
|                      |       |ODX{d}+---->|MDD{d}|                        |                 |
+----------------------+       +------+     +------+                        +-----------------+
@endditaa
