header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: The Contributors to Eclipse OpenSOVD
    software-name: opensovd-cda
    content: |
      # SPDX-FileCopyrightText: 2025 The Contributors to Eclipse OpenSOVD (see CONTRIBUTORS)
      #
      # SPDX-License-Identifier: Apache-2.0

  paths:
    - '**/*.toml'

