# Copyright (c) 2025-2026 The Contributors to Eclipse OpenSOVD (see CONTRIBUTORS)
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0

header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: The Contributors to Eclipse OpenSOVD
    software-name: opensovd-cda
    content: |
      Copyright (c) 2025-2026 The Contributors to Eclipse OpenSOVD (see CONTRIBUTORS)

      See the NOTICE file(s) distributed with this work for additional
      information regarding copyright ownership.

      This program and the accompanying materials are made available under the
      terms of the Apache License Version 2.0 which is available at
      https://www.apache.org/licenses/LICENSE-2.0

      SPDX-License-Identifier: Apache-2.0

  language:
    Rust:
      extensions:
        - .rs
      comment_style_id: SlashAsterisk

    ODX:
      type: data
      tm_scope: text.xml
      ace_mode: xml
      codemirror_mode: xml
      codemirror_mime_type: text/xml
      comment_style_id: AngleBracket
      extensions:
        - .odx-cs
        - .odx-c
        - .odx-d

  paths:
    - '**/*.toml'
    - '**/Dockerfile*'
    - '**/*.sh'
    - '**/*.py'
    - '**/*.yml'
    - '**/*.rs'
    - '**/*.yaml'
    - '**/*.adoc'
    - '**/*.odx*'
    - '**/*.kt'
