# SPDX-License-Identifier: Apache-2.0

exports_files([
    "Cargo.lock",
    "Cargo.toml",
])

alias(
    name = "cda_mbedtls",
    actual = "//cda-main:opensovd_cda_lib",
    visibility = ["//visibility:public"],
)

alias(
    name = "opensovd-cda",
    actual = "//cda-main:opensovd-cda",
    visibility = ["//visibility:public"],
)
