# SPDX-FileCopyrightText: 2026 Copyright (c) Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0

module(
    name = "classic-diagnostic-adapter",
    version = "0.1.0",
    bazel_compatibility = [">=8.6.0"],
)

bazel_dep(name = "rules_rust", version = "0.68.1-score")
bazel_dep(name = "mbedtls-rs", version = "0.1.0")
git_override(
    module_name = "mbedtls-rs",
    commit = "524e3b96ccad358b73e4e3ad706d15b8778845b9",
    remote = "https://github.com/eclipse-opensovd/mbedtls-rs.git",
)

rust = use_extension(
    "@rules_rust//rust:extensions.bzl",
    "rust",
    dev_dependency = True,
)
rust.toolchain(
    edition = "2024",
    versions = ["1.88.0"],
)
use_repo(rust, "rust_toolchains")

register_toolchains(
    "@rust_toolchains//:all",
    dev_dependency = True,
)

cda_crate_universe = use_extension(
    "@rules_rust//crate_universe:extensions.bzl",
    "crate",
    isolate = True,
)
cda_crate_universe.from_cargo(
    name = "cda_crates",
    cargo_lockfile = "//:Cargo.lock",
    manifests = ["//:Cargo.toml"],
    skip_cargo_lockfile_overwrite = True,
)
use_repo(cda_crate_universe, "cda_crates")

can_crate_universe = use_extension(
    "@rules_rust//crate_universe:extensions.bzl",
    "crate",
    isolate = True,
)
can_crate_universe.spec(
    package = "tokio-socketcan-isotp",
    git = "https://github.com/MarkSchmitt/tokio-socketcan-isotp.git",
    tag = "v0.6.0",
)
can_crate_universe.from_specs(
    name = "can_crates",
)
use_repo(can_crate_universe, "can_crates")
