= DoIP Communication

DoIP Communication is described in the ISO 13400 standard. Specific communication parameters and implementation details will be defined and linked in this document.

The communication parameters depend on the used logical link for the communication, itself will be filtered by configuration, and actual ecu detection/availability.

== Supported protocol versions

TODO

== Communication parameters

[cols="1,1,1,1"]
|===
|Name|Function|Default value|Comment

|CP_DoIPLogicalGatewayAddress|Logical address of a DoIP entity. In case of directly reachable DoIP entity it's equal to the CP_DoIPLogicalEcuAddress, otherwise data will be sent via this address to the CP_DoIPLogicalEcuAddress||
|CP_DoIPLogicalEcuAddress|Logical/Physical address of the ECU||
|CP_DoIPLogicalFunctionalAddress|Functional address of the ECU||
|CP_DoIPLogicalTesterAddress|Logical address of the tester||
|CP_DoIPNumberOfRetries|Number of retries for specific NACKs||NACK: OUT_OF_MEMORY (3)
|CP_DoIPDiagnosticAckTimeout|Maximum time the tester waits for an ACK or NACK of the DoIP entity||
|CP_DoIPRetryPeriod|Period between retries, after specific NACK conditions are encountered||
|CP_DoIPRoutingActivationTimeout|Maximum time allowed for the ECUs routing activation||
|CP_RepeatReqCountTrans|Number of retries in case a transmission error, a receive error, or transport layer timeout is encountered|0|
|CP_DoIPConnectionTimeout|Timeout after which a connection attempt should've been successful||
|CP_DoIPConnectionRetryDelay|Delay before attempting to reconnect|0|
|CP_DoIPConnectionRetryAttempts|Attempts to retry connection before giving up||
|===

=== connection establishment

.establishing doip connection
[plantuml, "Establish connection", svg]
----
@startuml
participant "CDA"
participant "DoIP-Entity" as ECU
group establish connection
    CDA -> ECU: connect
    activate ECU
    ECU -> CDA: success
    note right: Maximum of CP_DoIPConnectionTimeout
    deactivate ECU
end
group connection attempt fails / times out
    loop CP_DoIPConnectionRetryAttempts times
        note right of CDA:  Wait for CP_DoIPConnectionRetryDelay
        CDA -> ECU: connect
        activate ECU
        ECU -> CDA: success
        deactivate ECU
        note right: Maximum of CP_DoIPConnectionTimeout
        note right of CDA: break loop on success, continue on failure
    end
end
@enduml
----

Note: When these parameters are set via mdd, multiple mdd-files could match due to duplicated logical addresses.

TODO: specify resolving this behavior (e.g. use most lax settings?)

In case a connection was to be established as part of a diagnostic request, and a timeout is encountered, an error is reported on failure.

=== communication



