' SPDX-FileCopyrightText: 2026 Copyright (c) Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0

@startuml
title Data Read -- SID 22

participant Client
participant "HTTP Server\n(Axum)" as HTTP
participant "Security\nMiddleware" as SEC
participant "Data Handler" as HANDLER
participant "Diagnostic\nKernel" as DIAG
participant "UDS / DoIP" as COMM
participant ECU

Client -> HTTP : GET /components/{ecu}/data/{id}
activate HTTP

HTTP -> SEC : authenticate & authorize
activate SEC
SEC -> HTTP : OK
deactivate SEC

HTTP -> HANDLER : route to data handler
activate HANDLER

HANDLER -> DIAG : read data (service name, variant)
activate DIAG

DIAG -> DIAG : resolve service from MDD\n(short name -> SID 22 + DID)
DIAG -> DIAG : build UDS request payload\n(22 {DID})

DIAG -> COMM : send UDS request
activate COMM
COMM -> ECU : DoIP -> UDS ReadDataByIdentifier\n(22 {DID})
activate ECU
ECU -> COMM : positive response\n(62 {DID} {data})
deactivate ECU
COMM -> DIAG : raw UDS response
deactivate COMM

DIAG -> DIAG : decode UDS response\ninto named parameters\n(using MDD codec definitions)
DIAG -> HANDLER : decoded parameters
deactivate DIAG

HANDLER -> HANDLER : map parameters to\nSOVD JSON response
HANDLER -> HTTP : JSON body
deactivate HANDLER

HTTP -> Client : HTTP 200 OK\n{ "id": "...", "data": { ... } }
deactivate HTTP

@enduml
