FROM eclipse-temurin:21

RUN apt-get -y update && apt-get -y install tcpdump vim iproute2 jq

WORKDIR /app

COPY --chmod=755 docker/ipcli.sh /app/ipcli.sh
COPY --chmod=755 docker/entrypoint.sh /app/entrypoint.sh
COPY build/libs/ecu-sim-all.jar /app/ecu-sim-all.jar

ENTRYPOINT ["/app/entrypoint.sh"]
