# SPDX-License-Identifier: Apache-2.0

load("//bazel:rust_crate.bzl", "workspace_rust_library")

workspace_rust_library(
    name = "sovd_interfaces",
    srcs = glob(["src/**/*.rs"]),
    crate_deps = [
        "chrono",
        "schemars",
        "serde",
        "serde_json",
        "strum",
    ],
    crate_name = "sovd_interfaces",
    crate_root = "src/lib.rs",
    visibility = [
        "//cda-plugin-runtime-update:__pkg__",
        "//cda-plugin-security:__pkg__",
        "//cda-sovd:__pkg__",
    ],
    deps = [
        "//cda-interfaces:cda_interfaces",
    ],
)
