# SPDX-License-Identifier: Apache-2.0

load("//bazel:rust_crate.bzl", "workspace_rust_library")

workspace_rust_library(
    name = "cda_database",
    srcs = glob(["src/**/*.rs"]),
    crate_deps = [
        "bytes",
        "flatbuffers",
        "memmap2",
        "ouroboros",
        "prost",
        "schemars",
        "serde",
        "serde_json",
        "sha2",
        "tokio",
        "tracing",
        "uuid",
        "xz2",
    ],
    crate_name = "cda_database",
    crate_root = "src/lib.rs",
    visibility = [
        "//cda-core:__pkg__",
        "//cda-main:__pkg__",
        "//cda-plugin-runtime-update:__pkg__",
        "//cda-plugin-security:__pkg__",
    ],
    deps = [
        "//cda-interfaces:cda_interfaces",
    ],
)
