// Copyright (c) 2025 The Contributors to Eclipse OpenSOVD (see CONTRIBUTORS)
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available under the
// terms of the Apache License Version 2.0 which is available at
// https://www.apache.org/licenses/LICENSE-2.0
//
// SPDX-License-Identifier: Apache-2.0

[#_requirements_introduction]
= Introduction

The Classic Diagnostics Adapters purpose is to provide an SOVD API for legacy ECUs. Communication with legacy ECUs is facilitated by utilizing UDS. It must support DoIP, and may support additional transports in the future.

In this requirements documentation, the sections represent the functional requirements for the communication on both ends, and some generic requirements for the program itself.

The actual architecture and implementation details must be done in different documents for traceability and separation of concerns.
