[#_requirements_general]
= General

:numbered:

== Tracing
[.specitem, oft-sid="req~main.tracing.programmatically~1", oft-needs="impl"]

Tracing between requirements, architecture, design, implementation & tests is facilitated with https://github.com/itsallcode/openfasttrace[openfasttrace].


== Configuration
The CDA must support a configuration file that allows it to be configured to the use-cases of different users.

This includes, but is not limited to:

* network interfaces
* ports
* communication behaviour
** communication parameters (includes timeouts)
** initial discovery/detection of ecus

== Performance

The CDAs primary target is an embedded HPC that runs on the vehicle with Linux. Primary target architectures are aarch64, and x86_64. It should be noted, that those HPCs typically have lower memory and worse cpu performance to desktop machines, and run other (higher prioritized) software in parallel.

=== CPU & Memory

CPU and memory consumption need to be minimal to allow other tasks on that HPC to perform well.

=== Parallelity
:oft-title: req~general.performance.parallelity~1

The CDA must be able to communicate at least with 50 DoIP entities, and up to 200 ECUs behind those entities.

The maximum number of parallel threads used in the asynchronous
communication should be configurable.

== Modularity

The architecture must allow parts of it to be reusable for other use-cases. It's also required that the internal modules can be interchanged with other ones, by implementing the well-defined API of that module.

== Extensibility

=== Plugin system

A comprehensive plugin API must be provided, which allows vendors to extend the functionality.
