// Copyright (c) 2025 The Contributors to Eclipse OpenSOVD (see CONTRIBUTORS)
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available under the
// terms of the Apache License Version 2.0 which is available at
// https://www.apache.org/licenses/LICENSE-2.0
//
// SPDX-License-Identifier: Apache-2.0

[#_requirements_sovd]
= SOVD (ISO 17978-1)
:toc:
:toclevels: 3
:numbered:

The guiding principle behind this document is to specify the requirements for an ISO 17978-1 compatible API in the Eclipse OpenSOVD Classic Diagnostic Adapter (CDA).

== General
Paths and parameter names should be case-insensitive, unless otherwise mentioned.

== Technical
=== HTTP-Server
[.specitem, oft-sid="req~sovd.http.server.parallelity~1" oft-needs="arch"]

The HTTP Server has to support multiple connections, and calls should be handled asynchronously.

.Rationale
[.rationale]
Multiple clients might use the CDA at the same time, and asynchronous handling generally improves performance due to reduced thread count.


==== Configurable port
[.specitem, oft-sid="req~sovd.http.port.configurable~1" oft-needs="arch"]

The CDA must provide an HTTP- or HTTPS-server running on a configurable port.


=== HTTPS
[.specitem, oft-sid="req~sovd.https.certificate~1" oft-needs="arch"]

In case of HTTPS, the certificate/key must be providable through the configuration, or a plugin.

.Rationale
[.rationale]

Certificates/Keys might be stored in an HSM, therefore platform specific code might be needed for access.

#TODO# Maybe connection establishment/encryption also needs to be done through HSM?


== API

=== Entities

==== Data Types
[.specitem, oft-sid="req~sovd.api.data-types.mapping~1" oft-needs="arch"]

Data types must be mapped as specified by ISO 17978-3.

Additionally, for the data type `A_BYTEFIELD`, the format `hex` must be supported - see xref:_requirements_bytefield_as_hex[]

==== JSON data types
[.specitem, oft-sid="req~sovd.api.data-types.json~1" oft-needs="arch"]

Used JSON data types must be mapped as specified by ISO 17978-3.

=== Paths

==== Mapping of a standardized resource collection
[.specitem, oft-sid="req~sovd.api.standard-resource-collection-mapping~1" oft-needs="arch"]

The standardized resource collection for `/components/+{ecu-name}+` must be mapped as follows:

[cols="1,1,1"]
|===
|SID (base 16)|REST path|Comment

|10
| /modes/session
|

|11
| /operations/reset +
/status/restart
|

|14 +
19
| /faults/
|

|22 +
2E
| /data/+{data-identifier}+
/configurations/+{data-identifier}+
|category & classification between paths is handled by the functional class with configuration

|27
| /modes/security
|

|28
|/modes/commctrl
|

|29
| /modes/authentication
|

|31
| /operations/+{routine-identifier}+
|

|34 +
36 +
37
| /x-sovd2uds-download/requestdownload +
/x-sovd2uds-download/flashtransfer +
/x-sovd2uds-download/transferexit
| `flashtransfer` handles the whole transfer, not for individual calls

|3E
| --
| handled internally by CDA

|85
|/modes/dtcsetting
|

|===

NOTE: The mapping in ISO standard is inconsistent w.r.t. `/modes/security` and `/modes/authentication`

==== Operations

Operations (Routines SID 31~16~) can be synchronous or asynchronous. Asynchronous routines are routines, for which the `RequestResults` and/or `Stop` subfunctions are defined.

The order of operations:

1. `POST /executions` for *Start* (subfunction 01)
2. `GET /executions/+{id}+` for *RequestResults* (subfunction 03)
3. `DELETE /executions/+{id}+` for *Stop* (subfunction 02).

Synchronous routines:

The `POST` to executions will directly return the result - either a 200 with the data, or an error.

Example of a successful call:
[source,json]
----
{
  "parameters": {
      "key": "value"
  }
}
----

Asynchronous routines:

Since the response of the `Start` subfunction, as well as an id for polling the `RequestResults` subfunction are
required, both must be returned.

Example of a successful call:
[source,json]
----
{
  "id": "<id of created execution>",
  "status": "running",
  "parameters": {
      "key": "value"
  }
}
----

Should the call to the `Start` subfunction return an error (e.g. NRC), no `id` for polling is created.

There are however use-cases, in which you may want to call `RequestResults` or `Stop` independently, or there could
only be partial definitions (e.g. only Stop). For this use case the extension xref:_requirements_sovd_api_operations_extension[SOVD-API Extension for Operations] is required.


==== ECUs

=== Extensions to the ISO specification

[#_requirements_bytefield_as_hex]
==== Data Type A_BYTEFIELD
[.specitem, oft-sid="req~sovd.api.datatypes.hexoutput~1", oft-needs="arch"]

For the data type `A_BYTEFIELD` the json output type `string` with the format `hex` must be supported through an optional query-parameter. Using `hex` means, that the binary data must be base16-encoded, either with or without preceding `0x` prefixes.


.Rationale
[.rationale]
Handling base64 encoded binary directly can be compatibility challenge for offboard testers accessing the CDA. Manual debugging can also be simplified by directly seeing the hexadecimal encoded data, since it's easier to process for humans.

==== Mimetype application/octet-stream

The `/data/+{data-identifier}+` and `/operations/+{routine-identifier}+` endpoints must support the additional mimetype octet-stream where applicable, to allow clients to send and receive payloads as binary data.

NOTE: Only the payload is sent/received. The SID & DID/RID are derived from the path, and in case of NRCs only the NRC code (single byte) is sent back with a HTTP 502.

.Rationale
This requirement simplifies the use of the CDA as a diagnostic tester and in migration scenarios.

==== Operations
[#_requirements_sovd_api_operations_extension]

To support the use-case of calling `RequestResults` and `Stop`, without having to call `Start`,
the following boolean query parameters must be supported:

|===
|Method|Parameter|Description

|All
|x-sovd2uds-suppressService
|Suppresses sending the routine to the ECU

|DELETE
|x-sovd2uds-force
|Forces a DELETE operation to delete the id, regardless of an error the ecu might have reported for the `Stop` routine

|===

When a REST call is initiated that needs to call the service on the ECU, but is missing the required
definition in the diagnostic description, and `x-sovd2uds-suppressService` isn't set to true,
the REST call must fail.

==== Vehicle

A vehicle must support operations as a whole, to allow for operations which affect the whole vehicle, like updating
mdd-files, or reserve all ECUs for future use.

This requires a standardized resource collection in the exposed root path `/`.

The standardized resource collection must provide the following resources:

|===
|Resource|Description

|locks
|Locks affecting the whole vehicle

|functions
|Functions affecting the whole vehicle (i.e. functional communication)

|===

==== Functional communication

Functional communications needs to be possible. A standardized resource collection must be made available within the
`/functions/functionalgroups/+{groupName}+` resource.

The available functionality must be defined in an additional diagnostic description used solely for defining functional communication services. Since this file may contain multiple logical link definitions, a configuration option can be provided to filter the available links.

The following entities must be available in the functional groups resource collection:

|===
|Entity|Function

|locks
|Locking a functional group (also controls functional tester present)

|operations
|Calling functional routines

|data
|Calling functional data services

|modes
|Setting modes for the ecus in the functional group

|===

.Rationale
[.rationale]
Clients require functional communication to ECUs for use-cases, in which they want to control communication or dtcsettings for all ecus.

==== Flash API

===== General
[.specitem, oft-sid="req~sovd.api.flash-api~1", oft-needs="arch"]

A Flash-API is required to support flashing of ECUs, utilizing SIDs 34~16~, 36~16~ & 37~16~. It needs to enable efficient transfer of the data, without sending the individual data transfers via REST.

Flashing is the process of updating the firmware of an ECU.


.Rationale
[.rationale]
Handling for the aforementioned SIDs isn't defined in the ISO specification, it is however an important use-case to be able to update the firmware on ECUs.

===== Security
[.specitem, oft-sid="req~sovd.api.flashing.security~1", oft-needs="arch"]

The source of the data to be sent for flashing, must be restrictable to a path and its subdirectories via configuration.

.Rationale
[.rationale]
Without restrictions to the path, an attacker could exfiltrate arbitrary accessible data.


=== OpenAPI-Documentation

=== Security

Since vendors have different requirements and systems regarding security, security related functionality has to be implemented in a plugin.

==== Token validation
==== Audiences

== Standalone OpenAPI-Generator
[.specitem, oft-sid="req~sovd.api.openapi.generator~1"]

A standalone OpenAPI generator must be provided, which allows the creation of a full OpenAPI document for a single ECU, with a set of ECU variants, and audiences.
