' SPDX-FileCopyrightText: 2026 Copyright (c) Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0

@startuml
title Flash Data Transfer -- SID 34, 36, 37

participant Client
participant "HTTP Server\n(Axum)" as HTTP
participant "Security\nMiddleware" as SEC
participant "Flash Handler" as HANDLER
participant "Diagnostic\nKernel" as DIAG
participant "UDS / DoIP" as COMM
participant ECU

== 1. Request Download (SID 34) ==

Client -> HTTP : PUT /components/{ecu}/x-sovd2uds-download/requestdownload\n{ "requestdownload": { <param>: <value>, ... },\n  "flashClass": "<functional class>" (optional) }
activate HTTP

HTTP -> SEC : authenticate & authorize
activate SEC
SEC -> HTTP : OK
deactivate SEC

HTTP -> HANDLER : route to flash handler
activate HANDLER

HANDLER -> DIAG : lookup service\n(functional class = flashClass or configured default, SID 34)
activate DIAG
DIAG -> COMM : send UDS request
activate COMM
COMM -> ECU : DoIP -> UDS RequestDownload\n(34 {params})
activate ECU
ECU -> COMM : positive response\n(74 {blockSize info})
deactivate ECU
COMM -> DIAG : raw UDS response
deactivate COMM
DIAG -> HANDLER : response (max block size)
deactivate DIAG

HANDLER -> HTTP : JSON body
deactivate HANDLER
HTTP -> Client : HTTP 200 OK\n{ "requestdownload": { ... } }
deactivate HTTP

== 2. Transfer Data (SID 36) ==

Client -> HTTP : POST /components/{ecu}/x-sovd2uds-download/flashtransfer\n{ "id": "<file-id>", "offset": ..., "length": ...,\n  "blocksize": ..., "blocksequencecounter": ...,\n  "flashClass": "<functional class>" (optional) }
activate HTTP

HTTP -> SEC : authenticate & authorize
activate SEC
SEC -> HTTP : OK
deactivate SEC

HTTP -> HANDLER : route to flash handler
activate HANDLER

HANDLER -> DIAG : lookup service\n(functional class = flashClass or configured default, SID 36)
activate DIAG
DIAG -> HANDLER : service found
deactivate DIAG

HANDLER -> HANDLER : start background transfer\nfrom configured flash folder
HANDLER -> HTTP : JSON body (transfer id)
deactivate HANDLER
HTTP -> Client : HTTP 200 OK\n{ "id": "<transfer-id>" }
deactivate HTTP

loop for each block-sized chunk (background)
    HANDLER -> DIAG : transfer data block
    activate DIAG
    DIAG -> COMM : send UDS request
    activate COMM
    COMM -> ECU : DoIP -> UDS TransferData\n(36 {seqNo} {block data})
    activate ECU
    ECU -> COMM : positive response\n(76 {seqNo})
    deactivate ECU
    COMM -> DIAG : raw UDS response
    deactivate COMM
    DIAG -> HANDLER : block confirmed
    deactivate DIAG
end

Client -> HTTP : GET /components/{ecu}/x-sovd2uds-download/flashtransfer/{id}
HTTP -> Client : HTTP 200 OK\n{ "id", "fileId", "status", "acknowledgedBytes", ... }

== 3. Transfer Exit (SID 37) ==

Client -> HTTP : PUT /components/{ecu}/x-sovd2uds-download/transferexit\n{ "flashClass": "<functional class>" } (optional body)
activate HTTP

HTTP -> SEC : authenticate & authorize
activate SEC
SEC -> HTTP : OK
deactivate SEC

HTTP -> HANDLER : route to flash handler
activate HANDLER

HANDLER -> DIAG : lookup service\n(functional class = flashClass or configured default, SID 37)
activate DIAG
DIAG -> COMM : send UDS request
activate COMM
COMM -> ECU : DoIP -> UDS RequestTransferExit\n(37)
activate ECU
ECU -> COMM : positive response\n(77)
deactivate ECU
COMM -> DIAG : raw UDS response
deactivate COMM
DIAG -> HANDLER : transfer exit confirmed
deactivate DIAG

HANDLER -> HTTP : no content
deactivate HANDLER
HTTP -> Client : HTTP 204 No Content
deactivate HTTP

== 4. Remove finished transfer ==

Client -> HTTP : DELETE /components/{ecu}/x-sovd2uds-download/flashtransfer/{id}
activate HTTP
HTTP -> HANDLER : remove finished / aborted transfer
activate HANDLER
HANDLER -> HTTP : removed
deactivate HANDLER
HTTP -> Client : HTTP 204 No Content
deactivate HTTP

@enduml
