[#_architecture_sovd_api_iso_extensions_functional_comm]
= Functional communication
:toc:
:numbered:
ifndef::rootpath[]
:rootpath: ../../..
endif::rootpath[]

== Diagnostic description & Configuration

Information about the available functional groups, the available services in those groups, and their communication parameters must be provided in a separate diagnostic description.

'''

The diagnostic descriptions mdd filename, in which the information for functional communication is contained, must be configurable. When no file is configured, functional communication is not available.

[.specitem, oft-sid="arch~functional.communication.configuration.diagnosticdescription~1"]

'''

A configuration option in the CDA can further filter the available functional groups from the diagnostic description.

[.specitem, oft-sid="arch~functional.communication.configuration.groupfilter~1"]

To represent the standardized resource collection for functional communication, it's challenging and non-transparent to extract common functional services from all ECU files.

.Rationale
Follows the general pattern of one mdd file result in an available standardized resource collection.

== API

Functional group functionality - if available - must be available in the `/functions/functionalgroups/+{group-name}+` path.

Within that path, a standardized resource collection (chapter 5.4.2 in ISO/DIS 17978-3) must be available, with the following semantics.

=== Locks

Locking a functionalgroup will start the sending of functional Tester Presents to the functional DoIP addresses of all DoIP Entities, and stop sending of non-functional tester-presents.

==== Lock Options

There must be an option to restore the previous ECU-Locks (and their tester presents).

=== Data

NOTE: The content-type `application/octet-stream` is only supported for requests.

Since functional communication returns data from multiple ECUs, the `/data/+{data-identifier}+` endpoint must return within the top-level of `data` the name of the ECU as key, and only then its returned data (if any) as value.

In case of errors, the `errors` structures must still return the type `DataError[]`. Inside a `DataError`, the json-pointer must always point to the `data/+{ecu-name}+/...` element (including the ECU-Name), or in case of communication/timeout errors, just to the ECU-Entry `/data/+{ecu-name}+`. A regular GenericError response with a failing HTTP Status Code (4xx, 5xx) is only acceptable, when no communication was performed, and the request failed beforehand.


=== Operations

NOTE: The content-type `application/octet-stream` is only supported for requests.

Same principle as with data, except that the top level element name is `parameters`.
