[#_architecture_sovd_api_iso_extensions_comparams]
= Communication Parameters (ComParams)
:toc:
:numbered:

ifndef::rootpath[]
:rootpath: ../../..
endif::rootpath[]

Communication parameter handling is exposed through a `comparam` endpoint in `operations`.

== Motivation

When using the CDA to communicate with classic ECUs, a client needs the ability to modify the communication parameters like timeouts and retries on-the-fly. This API provides a way to do this.

== Retrieving & Modifying with a lock

|===
|Method|Path|Description

|POST
|/operations/comparam/executions
|Creates an id, can also directly contain parameters to be modified

|GET
|/operations/comparam/executions/+{id}+
|Returns the current communication parameters

|PUT
|/operations/comparam/executions/+{id}+
|Modifies the communication parameters

|DELETE
|/operations/comparam/executions/+{id}+
|Resets the communication parameters to their original state

|===

These operations require a lock on the entity. Only one execution of communication parameters per entity is allowed.

== Retrieving without a lock

NOTE: This is a small extension to the ISO standard

To allow retrieving the communication parameters without a lock, a GET on `/operations/comparam` must also return the current parameters.

.Rationale

Clients without a lock might want to log the current communication parameters for informational
purposes, so they should be able to retrieve them.

Handling this with the POST/GET semantic with only a single execution would make the handling
extremely complicated for parallel clients with & without locks.

Example for directly retrieving communication parameters:

[source, json]
----
{
  "item": {
    "id": "comparam",
    "name": "Communication parameters",
    "asynchronous_execution": true,
    "proximity_proof_required": false
  },
  "parameters": {
    "CP_P6Max": {
      "value": "4500000",
      "unit": {
        "factor_to_si_unit": 1e-06
      }
    },
    "CP_RC78Handling": {
      "value": "Continue until RC78 timeout"
    },
    "...": {
      "...": "..."
    }
  }
}
----

#TODO# openapi schema

#TODO# Maybe move unit/types into schema with include-schema?
