openapi: 3.1.0
info:
  version: 0.0.1
  title: Endpoints related to embedded files in mdd

tags:
  - name: mdd-embedded-files
    description: Endpoints related to embedded files in mdd

components:
  schemas:
    MddEmbeddedFilesListEntry:
      type: object
      required:
        - id
        - x-sovd2uds-OrigPath
        - size
      properties:
        id:
          type: string
        mimetype:
          type: string
          description: "Mimetype of the file"
        size:
          type: integer
          description: "Size of the file"
        x-sovd2uds-OrigPath:
          type: string
          description: "Original path of the file, as named by odx-converter"

    MddEmbeddedFilesList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/MddEmbeddedFilesListEntry"

paths:
  /components/{ecu-name}/x-sovd2uds-bulk-data/mdd-embedded-files:
    parameters:
      - $ref: "common.yaml#/components/parameters/EcuName"
    get:
      summary: "Retrieves list of embedded files"
      tags:
        - mdd-embedded-files
      responses:
        "200":
          description: "Successful request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MddEmbeddedFilesList"

  /components/{ecu-name}/x-sovd2uds-bulk-data/mdd-embedded-files/{id}:
    parameters:
      - $ref: "common.yaml#/components/parameters/EcuName"
      - name: id
        in: query
        schema:
          type: string
    get:
      summary: "Retrieves list of single ecu jobs"
      tags:
        - mdd-embedded-files
      responses:
        "200":
          description: "Successful request"
          content:
            "*":
              description: "File contents with the mimetype that matches the content, as determined by odx-converter. application/octet-stream of nothing is defined)"
        "404":
          description: "Embedded file not found"
        default:
          $ref: "common.yaml#/components/responses/SovdGenericErrorResponse"
