/*
 * SPDX-FileCopyrightText: 2026 Copyright (c) Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * SPDX-License-Identifier: Apache-2.0
 */

//! REST API for the ECU simulator with OpenAPI/Swagger support.
//!
//! The OpenAPI spec is generated by aide from the routes and the
//! `schemars::JsonSchema` derives on the API types - see [`openapi::api_docs`].

mod handlers;
mod openapi;
mod routes;
mod types;

use std::sync::Arc;

use aide::{axum::routing, openapi::OpenApi, swagger::Swagger};
use axum::{Extension, Json};
pub use routes::create_router;
pub use types::*;

use crate::simulator::SimulatorState;

/// Swagger UI route
pub const SWAGGER_UI_ROUTE: &str = "/swagger-ui";
/// OpenAPI JSON route
pub const OPENAPI_JSON_ROUTE: &str = "/openapi.json";

/// Launch the REST API server.
pub async fn launch_api_server(
    address: &str,
    port: u16,
    state: Arc<SimulatorState>,
) -> Result<(), crate::error::SimulatorError> {
    let listen_addr = format!("{address}:{port}");
    let server_url = format!("http://{address}:{port}");

    let mut api = OpenApi::default();
    let app = create_router(Arc::clone(&state))
        .route(
            SWAGGER_UI_ROUTE,
            Swagger::new(OPENAPI_JSON_ROUTE).axum_route(),
        )
        .route(
            OPENAPI_JSON_ROUTE,
            routing::get(
                |Extension(api): Extension<Arc<OpenApi>>| async move { Json((*api).clone()) },
            ),
        )
        .finish_api_with(&mut api, |api| openapi::api_docs(api, server_url))
        .layer(Extension(Arc::new(api)));

    tracing::info!(address = %listen_addr, "Starting REST API server");

    let listener = tokio::net::TcpListener::bind(&listen_addr)
        .await
        .map_err(|e| crate::error::SimulatorError::ApiServer(e.to_string()))?;

    axum::serve(listener, app)
        .await
        .map_err(|e| crate::error::SimulatorError::ApiServer(e.to_string()))?;

    Ok(())
}
