# SPDX-License-Identifier: Apache-2.0

load("//bazel:rust_crate.bzl", "workspace_rust_library")

workspace_rust_library(
    name = "cda_health",
    srcs = glob(["src/**/*.rs"]),
    crate_deps = [
        "aide",
        "axum",
        "chrono",
        "futures",
        "schemars",
        "serde",
        "thiserror",
        "tokio",
    ],
    crate_name = "cda_health",
    crate_root = "src/lib.rs",
    proc_macro_crate_deps = ["async-trait"],
    visibility = ["//cda-main:__pkg__"],
    deps = [
        "//cda-interfaces:cda_interfaces",
        "//cda-sovd:cda_sovd",
    ],
)
