# SPDX-FileCopyrightText: 2026 Copyright (c) Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0

name: Nightly Advisories, Clippy and Format Checks

on:
  schedule:
    - cron: "0 4 * * *" # Daily at 04:00 UTC
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  versions:
    uses: ./.github/workflows/tool-versions.yml

  advisories:
    needs: versions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: false
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ needs.versions.outputs.stable }}
      - name: Setup devenv
        run: make setup-devenv
      - name: Check advisories
        run: make deny ARGS=advisories
  nightly_clippy:
    needs: versions
    runs-on: ubuntu-latest
    name: "Nightly Lint and Format"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: false
      - name: Setup DLT tracing lib
        uses: eclipse-opensovd/dlt-tracing-lib/.github/actions/setup-dlt@main
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: ${{ needs.versions.outputs.protoc }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Format and Clippy - Nightly toolchain pinned
        uses: eclipse-opensovd/cicd-workflows/rust-lint-and-format-action@febc566231f4ff6fafec78c91078e381666120f9
        with:
          toolchain: ${{ needs.versions.outputs.nightly }}
          extra-args: "--all-features --all-targets -- --deny=warnings"
      - name: Format and Clippy - Nightly toolchain latest
        if: ${{ !cancelled() }}
        continue-on-error: true
        uses: eclipse-opensovd/cicd-workflows/rust-lint-and-format-action@febc566231f4ff6fafec78c91078e381666120f9
        with:
          toolchain: nightly
          extra-args: "--all-features --all-targets"
